# Generated by Django 5.0.3 on 2024-04-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_review_app', '0002_review_star_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star_rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('review', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_review_app.review')),
            ],
        ),
    ]
