# Generated by Django 5.0.3 on 2024-04-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_review_app', '0005_alter_review_would_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
