# Generated by Django 5.0.3 on 2024-04-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_review_app', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
