# Generated by Django 5.0.3 on 2024-04-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_review_app', '0011_isownerpermission_rename_user_review_reviewuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsOwnerPermission',
        ),
    ]
